# Generated by Django 6.0 on 2025-12-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_notification_emailed_and_triggers'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='clinic_pass_user_id_5b5912_idx',
            old_name='clinic_pass_user_id_3e2f1b_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='clinic_pass_expires_ea5410_idx',
            old_name='clinic_pass_expires_2a19f1_idx',
        ),
    ]
