# Generated by Django 6.0 on 2025-12-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_rename_clinic_pass_user_id_3e2f1b_idx_clinic_pass_user_id_5b5912_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='branch',
            field=models.CharField(choices=[('rembo', 'Rembo'), ('taguig', 'Taguig'), ('pasig', 'Pasig')], default='rembo', help_text='Preferred vet clinic branch location', max_length=20),
        ),
    ]
