# Generated by Django 6.0 on 2025-12-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_owner_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='branch',
            field=models.CharField(choices=[('taguig', 'Taguig'), ('pasig', 'Pasig'), ('makati', 'Makati')], default='taguig', help_text='Preferred vet clinic branch location', max_length=20),
        ),
    ]
