# Generated by Django 6.0 on 2025-12-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_update_branches_remove_rembo_add_makati'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerRegistrationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('registration_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('otp_verified', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'is_used'], name='clinic_owne_email_00229f_idx'), models.Index(fields=['expires_at'], name='clinic_owne_expires_6081b1_idx')],
            },
        ),
    ]
