# Generated by Django 6.0 on 2026-01-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_add_missed_status_to_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='custom_species',
            field=models.CharField(blank=True, help_text="Specify if 'Other' is selected", max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('fish', 'Fish'), ('turtle', 'Turtle'), ('other', 'Other')], default='dog', max_length=20),
        ),
    ]
