# Generated by Django 6.0 on 2025-12-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0002_veterinarian_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='access_code',
            field=models.CharField(blank=True, help_text='Unique access code required for login (in addition to password)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='personal_email',
            field=models.EmailField(blank=True, help_text='Personal email for sending access code and notifications', max_length=254),
        ),
    ]
