# Generated by Django 6.0 on 2025-12-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0003_veterinarian_access_code_veterinarian_personal_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetRegistrationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('personal_email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('registration_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
