# Generated by Django 6.0 on 2025-12-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0004_vet_registration_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='branch',
            field=models.CharField(choices=[('rembo', 'Rembo'), ('taguig', 'Taguig'), ('pasig', 'Pasig')], default='rembo', help_text='Branch location where this veterinarian is registered', max_length=20),
        ),
    ]
