# Generated by Django 6.0 on 2025-12-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0005_veterinarian_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarian',
            name='branch',
            field=models.CharField(choices=[('taguig', 'Taguig'), ('pasig', 'Pasig'), ('makati', 'Makati')], default='taguig', help_text='Branch location where this veterinarian is registered', max_length=20),
        ),
    ]
