# Generated by Django 6.0 on 2026-01-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0007_add_superadmin_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='last_email_change',
            field=models.DateTimeField(blank=True, help_text='Last time email was changed', null=True),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='last_password_change',
            field=models.DateTimeField(blank=True, help_text='Last time password was changed', null=True),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='last_username_change',
            field=models.DateTimeField(blank=True, help_text='Last time username was changed', null=True),
        ),
    ]
